name: Build Kotlin Project with Gradle

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'  # Trigger on version tags
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Set up Android SDK
      uses: reactivecircus/android-sdk-actions@v3
      with:
        ndk-version: '27.0.12077973'
        sdk-packages: 'platforms;android-28'

    - name: Create or update local.properties
      run: |
        echo "sdk.dir=${{ env.ANDROID_HOME }}" > local.properties
        echo "ndk.dir=${{ env.ANDROID_NDK_HOME }}" >> local.properties

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build AAR with Gradle
      run: ./gradlew clean assembleRelease

    - name: Run tests
      run: ./gradlew test

    - name: Upload AAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: aar-file
        path: app/build/outputs/aar/*.aar

    - name: Create GitHub Release
      id: create_release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: gh-action/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload AAR to GitHub Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: gh-action/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app/build/outputs/aar/*.aar
        asset_name: customtabs-release.aar
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
